spring:
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?reWriteBatchedInserts=true"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  kafka:
    bootstrap-servers: localhost:9092
    group-id: regulus-maximus
    topics:
      mottatt-sykmelding: tsm.mottak-sykmelding
      sykmelding-med-utfall: tsm.mottak-sykmelding-med-utfall
    consumer:
      max-poll-records: 1
      auto-offset-reset: none
      enable-auto-commit: false
