spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/my_database
    username: my_user
    password: my_password
  flyway:
    url: jdbc:postgresql://localhost:5432/my_database
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    group-id: regulus-maximus
    topics:
      mottatt-sykmelding: tsm.mottak-sykmelding
      sykmelding-med-utfall: tsm.mottak-sykmelding-med-utfall
      tsm-sykmelding: tsm.sykmelding
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 1
      auto-offset-reset: none
      enable-auto-commit: true
  sql:
    init:
      mode: always
server:
  port: 8080
