ktor:
  environment: local
  application:
    modules:
      - no.nav.tsm.mottak.ApplicationKt.module
  deployment:
    port: 8080
  database:
    dbUrl: postgresql://$DB_HOST:$DB_PORT/$DB_DATABASE
    dbUser: $DB_USERNAME
    dbPassword: $DB_PASSWORD
