ktor:
  environment: local
  development: true
  application:
    modules:
      - no.nav.tsm.mottak.ApplicationKt.module
  deployment:
    port: 8080
  database:
    dbUser: postgres
    dbPassword: postgres
    dbHost: localhost
    dbPort: 5432
    dbName: postgres
